import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#131313",
        "tertiary": "#ffb870",
        "surface-container-high": "#2a2a2a",
        "surface-tint": "#c6c6c7",
        "primary-fixed": "#e2e2e2",
        "surface": "#131313",
        "on-primary-fixed-variant": "#454747",
        "secondary": "#e9c176",
        "surface-dim": "#131313",
        "on-secondary-fixed-variant": "#5d4201",
        "on-secondary-fixed": "#261900",
        "on-surface-variant": "#c4c7c7",
        "tertiary-container": "#2a1500",
        "on-surface": "#e5e2e1",
        "outline-variant": "#444748",
        "on-tertiary-container": "#be7000",
        "inverse-primary": "#5d5f5f",
        "outline": "#8e9192",
        "on-tertiary": "#4a2800",
        "inverse-on-surface": "#313030",
        "surface-bright": "#393939",
        "on-background": "#e5e2e1",
        "surface-variant": "#353535",
        "on-primary-fixed": "#1a1c1c",
        "primary": "#c6c6c7",
        "error": "#ffb4ab",
        "primary-container": "#181a1b",
        "surface-container": "#20201f",
        "tertiary-fixed-dim": "#ffb870",
        "on-secondary": "#412d00",
        "on-tertiary-fixed": "#2c1600",
        "secondary-fixed": "#ffdea5",
        "on-error": "#690005",
        "inverse-surface": "#e5e2e1",
        "secondary-container": "#604403",
        "primary-fixed-dim": "#c6c6c7",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-fixed": "#ffdcbe",
        "surface-container-low": "#1c1b1b",
        "secondary-fixed-dim": "#e9c176",
        "on-primary-container": "#818383",
        "on-primary": "#2f3131",
        "on-secondary-container": "#dab36a",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-container-highest": "#353535",
        "on-tertiary-fixed-variant": "#693c00"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Space Grotesk"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
} satisfies Config;
